Ass03.PL/ViewModels/EmployeeViewModel.cs
using Demo.DAL.Data.Models;
using System.ComponentModel.DataAnnotations;
using System;
using Microsoft.AspNetCore.Http;

namespace Demo.PL.ViewModels
{
    public class EmployeeViewModel
    {

        public int Id { get; set; }


        [Required(ErrorMessage = "Name Is Required!")]
        [MinLength(5), MaxLength(50)]
        public string Name { get; set; }

        public IFormFile Image { get; set; }

        public string ImageName { get; set; }

        [Range(22, 30)]
        public int? Age { get; set; }

        [RegularExpression(@"^[0-9]{1,3}-[a-zA-Z]{5,10}-[a-zA-Z]{5,10}-[a-zA-Z]{5,10}$"
        , ErrorMessage = "Address must be like 123-Street-City-Country")]
        public string Address { get; set; }

        [DataType(DataType.Currency)]
        public decimal Salary { get; set; }

        public bool IsActive { get; set; }


        [EmailAddress]
        public string Email { get; set; }

        [Phone]
        public string PhoneNumber { get; set; }

        public DateTime HireDate { get; set; }

        public int DepartmentId { get; set; }
        public virtual Department Department { get; set; }
    }
}

Ass03.PL/Controllers/DepartmentController.cs
using Demo.BLL.Interfaces;
using Demo.BLL.Repostioris;
using Demo.DAL.Data.Models;
using Demo.PL.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    //[ValidateAntiForgeryToken]
    public class DepartmentController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public DepartmentController(IMapper mapper, IUnitOfWork unitOfWork)
        {
            this._mapper = mapper;
            this._unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index()
        {
            var departments = await _unitOfWork.DeparmentRepositry.GetAll();

            var departmentsVM =  _mapper.Map<IEnumerable<Department>, IEnumerable<DepartmentViewModel>>(departments);

            return View(departmentsVM);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(DepartmentViewModel departmentVM)
        {
            if (ModelState.IsValid)
            {
                var department = _mapper.Map<DepartmentViewModel, Department>(departmentVM);
                _unitOfWork.DeparmentRepositry.Add(department);
                var count = await _unitOfWork.Complete();
                if (count > 0)
                    TempData["Messege"] = "The Department Created Succesfuly!";
                else
                    TempData["Messege"] = "Error Occured !..The Department not Created!";


                return RedirectToAction(nameof(Index));
            }

            return View(departmentVM);
        }

        public async Task<IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var department = await _unitOfWork.DeparmentRepositry.Get(id.Value);
            if (department is null)
                return NotFound();

            var departmentVM = _mapper.Map<Department, DepartmentViewModel>(department);
            return View(ViewName, departmentVM);

        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return BadRequest();

            return await Details(id.Value, "Edit");


        }
        [HttpPost]
        public IActionResult Edit([FromRoute] int id, DepartmentViewModel departmentVM)
        {
            //if (id !=department.Id)
            //    return BadRequest();
            if (ModelState.IsValid)
            {

                try
                {
                    var department = _mapper.Map<DepartmentViewModel, Department>(departmentVM);
                    _unitOfWork.DeparmentRepositry.Update(department);
                    _unitOfWork.Complete();

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                    throw;
                }
            }

            return View(departmentVM);


        }

        public async Task<IActionResult> DeleteAsync(int? id)
        {
            if (id is null)
                return BadRequest();

            return  await Details(id.Value, "Delete");


        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id, DepartmentViewModel departmentVM)
        {
            //if (id != departmentVM.Id)
            //    return BadRequest();
            if (ModelState.IsValid)
            {

                try
                {
                    var department = _mapper.Map<DepartmentViewModel, Department>(departmentVM);

                    _unitOfWork.DeparmentRepositry.Delete(department);
                   await _unitOfWork.Complete();

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                    throw;
                }
            }

            return View(departmentVM);


        }


    }
}

Ass03.PL/Controllers/EmployeeController.cs
using Demo.BLL.Interfaces;
using Demo.BLL.Repostioris;
using Demo.DAL.Data.Models;
using Demo.PL.Helpers;
using Demo.PL.ViewModels;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public EmployeeController(IMapper mapper,IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            this._unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index(string searchInp)
        {
            var employees = Enumerable.Empty<Employee>();

            if (!string.IsNullOrEmpty(searchInp))
                employees = _unitOfWork.EmployeeRepository.SearchByName(searchInp.ToLower());
            else
             employees = await _unitOfWork.EmployeeRepository.GetAll();


            var empsVM = _mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(employees);

            return View(empsVM);
        }

        [HttpGet]
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employeeVM)
        {
            employeeVM.ImageName =  await DocumentSetting.UploadFile(employeeVM.Image, "images");
            if (ModelState.IsValid)
            {
                var employee = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);

                _unitOfWork.EmployeeRepository.Add(employee);

                await _unitOfWork.Complete();
                return RedirectToAction(nameof(Index));
            }

            return View(employeeVM);
        }

        public async Task<IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id is null)
                return BadRequest();
            var employee =  await _unitOfWork.EmployeeRepository.Get(id.Value);
            if (employee is null)
                return NotFound();
            var employeeVM = _mapper.Map<Employee, EmployeeViewModel>(employee);

            return View(ViewName, employeeVM);

        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null)
                return BadRequest();

            return  await Details(id.Value, "Edit");


        }
        [HttpPost]
        public async Task<IActionResult> Edit([FromRoute] int id, EmployeeViewModel employeeVM)
        {
 
            if (ModelState.IsValid)
            {

                try
                {
                    var oldEmployee = await _unitOfWork.EmployeeRepository.Get(employeeVM.Id);
                   
                    if(!string.IsNullOrEmpty(oldEmployee.ImageName))
                        DocumentSetting.DeleteFile(oldEmployee.ImageName, "images");
                       employeeVM.ImageName=await DocumentSetting.UploadFile(employeeVM.Image, "images");
                    
                    var employee = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                    _unitOfWork.EmployeeRepository.Update(employee);
                    await _unitOfWork.Complete();


                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                    throw;
                }
            }

            return View(employeeVM);


        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null)
                return BadRequest();


            return await Details(id:id.Value, "Delete");


        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int id, EmployeeViewModel employeeVM)
        {
            //if (id != employee.Id)
            //    return BadRequest();
            if (ModelState.IsValid)
            {

                try
                {
                    var employee = _mapper.Map<EmployeeViewModel, Employee>(employeeVM);
                    _unitOfWork.EmployeeRepository.Delete(employee);
                    var count = await _unitOfWork.Complete();
                    if (count > 0)
                        DocumentSetting.DeleteFile(employee.ImageName, "images");
                    return RedirectToAction(nameof(Index));
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, e.Message);
                    throw;
                }
            }

            return View(employeeVM);


        }


    }
}

Ass03.PL/Views/Employee/Create.cshtml
@model EmployeeViewModel

@{
    ViewData["Title"] = "Create";

}

<h1>Create New Employee</h1>

<div class="mt-3">
    <form class="form-group" asp-action="Create" enctype="multipart/form-data">

        <partial name="PartialViews/EmployeeCreateEditViewPartial" />

        <input  type="submit" value="Submit"  class="btn btn-primary"/>|
        <a asp-controller="Employee" asp-action="Index">Back To List</a>

        
   </form>

</div>


@section  ClintSideValidation{

    <partial name="_ValidationScriptsPartial" />
}

Ass03.PL/Views/Employee/Delete.cshtml
@model EmployeeViewModel;
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Department</h1>
<form class="form-group" asp-action="Delete">

    <partial name="PartialViews/EmployeeDeleteDetailsViewPartial" model="Model" />

    <input hidden asp-for="ImageName" />

<input type="submit" value="Delete" class="btn btn-primary" />|
<a asp-controller="Department" asp-action="Index">Back To List</a>
</form>

Ass03.PL/Views/Employee/Details.cshtml
@model EmployeeViewModel;
@{
    ViewData["Title"] = "Derails";
}

<h1>Employee Details</h1>

<partial name="PartialViews/EmployeeDeleteDetailsViewPartial" model="Model" />

<input type="submit" value="Edite" class="btn btn-primary" />|
<a asp-controller="Department" asp-action="Index">Back To List</a>

Ass03.PL/Views/Employee/Edit.cshtml
@model EmployeeViewModel
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Employee</h1>
<br />
<form class="form-group" asp-action="Edit" enctype="multipart/form-data" >
    <div asp-validation-summary="All"></div>

    <partial name="PartialViews/EmployeeCreateEditViewPartial" model="Model" />

    <input type="submit" value="Save" class="btn btn-primary" />|
    <a asp-controller="Employee" asp-action="Index">Back To List</a>


</form>

@section  ClintSideValidation{

    <partial name="_ValidationScriptsPartial" />
}

Ass03.PL/Views/Employee/Index.cshtml
@model IEnumerable<EmployeeViewModel>;
@{
    ViewData["Title"] = "Index";
}

<h1>All employees</h1>

<br />
<a asp-action="Create" class="mt-4 btn btn-primary">Create New employee</a>

<br />
<br />

<div class="row justify-content-center align-items-center mt-5">

    <form asp-action="Index" class="row col-8 offset-1">

        <div class="col-8">
            <input class="form-control" type="text" name="searchInp" placeholder="Search by Name..." />
        </div>

        <div class="col-4">
            <input value="Search" type="submit" class="btn btn-success" />
        </div>
    </form>
</div>

@if (Model.Count() > 0)
{


    <div class="mt-4">
        <table class="table tabletable-striped table-hover">
            <thead>
                <tr>

                    <td>@Html.DisplayNameFor(E=>E.Name)</td>
                    <td>Image</td>
                    <td>@Html.DisplayNameFor(E=>E.Age)</td>
                    <td>@Html.DisplayNameFor(E=>E.Address)</td>
                    <td>@Html.DisplayNameFor(E=>E.Salary)</td>
                    <td>@Html.DisplayNameFor(E=>E.IsActive)</td>
                    <td>@Html.DisplayNameFor(E=>E.Email)</td>
                    <td>@Html.DisplayNameFor(E=>E.PhoneNumber)</td>
                    <td>@Html.DisplayNameFor(E=>E.HireDate)</td>

                    <td> Details</td>
                    <td> Update </td>
                    <td> Delete </td>

                </tr>
            </thead>
            <tbody>
                @foreach (var employee in Model)
                {
                    <tr>
                        <td> @Html.DisplayFor(e=>employee.Name)</td>
                        <td>

                            <img src="~/files/images/@employee.ImageName" width="75" class="img-fluid rounded-circle" />
                        </td>
                        <td> @Html.DisplayFor(e=>employee.Age) </td>
                        <td> @Html.DisplayFor(e=>employee.Address) </td>
                        <td> @Html.DisplayFor(e=>employee.Salary) </td>
                        <td> @Html.DisplayFor(e=>employee.IsActive) </td>
                        <td> @Html.DisplayFor(e=>employee.Email) </td>
                        <td> @Html.DisplayFor(e=>employee.PhoneNumber) </td>
                        <td> @Html.DisplayFor(e=>employee.HireDate) </td>


                        <partial name="_ButtonsPartial" model="@employee.Id.ToString()" />

                    </tr>

                }
            </tbody>
        </table>

    </div>

}
else
{
    <div class="mt-2 ">
        <h1>Thers is No employees !</h1>
    </div>
}